### PR TITLE
Added DefaultAssembly parameter

### PR DESCRIPTION
**Pull request by aravol**
This will allow compilation of XAML files which use clr-namespace references from within their own assembly, which are not allowed to have assembly directives under WPF.

### CODE REVIEW

**Comment by aravol** [comment]
Turn out that while this is generating seemingly valid XAML, the parser continues to fail, probably because the requested dll isn't actually referenced

**Comment by aravol** [comment]
Further testing into breaks has been done - the current branch is working, but only in debug configuration (hosting from VS doesn't seem to matter). Reopening the pull request for now, but more work is likely needed.

**Comment by aravol** [comment]
Merging and resolving a small conflict - still would like to see this included with the main build

**Comment by EmptyKeys** [comment]
I thought you are still working on it. I will test it and add that to next version. :)

**Comment by aravol** [comment]
My apologies for not being clearer sooner - there was a break, but I couldn't reproduce it after a rebuild, so I reopened. All's well now, hope to see this functionality soon

**Pull request merged**
