### PR TITLE
Added Namespace property to UIRoot

### PR DESCRIPTION
**Pull request by ala53**
Hello,
I had an idea to make CodeBehind layers easier. If a "Namespace" property is added to UIRoot, then you can specify the namespace to generate the code in - E.g.

```
<ek:UIRoot 
     ...bla bla bla...
     Namespace="MyApp.MonoGame.UI.Core"
```
Then, the generator generates a `MyApp.MonoGame.UI.Core.MyUIPage` class rather than an `EmptyKeys.UserInterface.Generated.MyUIPage` class, which makes the CodeBehind match up a bit better.

### CODE REVIEW

**Comment by EmptyKeys** [comment]
Hmm nice :) I can see that could be useful in some scenarios. Tho you would have to add using to Generated namespace in case of merged dictionaries. 

What about bit more generic solution, another optional command line option perhaps?

**Comment by ala53** [comment]
You're right, that probably would work better. I originally tried to hook into the `x:Class` (auto-generated by VS) but couldn't find a way to access it, so this is almost as good. 

How does this look? (I also did a slight modification to print all possible `RenderMode` values rather than hard coding the "SunBurn/MonoGame" value)

**Comment by EmptyKeys** [comment]
looks good, I will include that in next major version

**Comment by ala53** [comment]
Well, I was trying to make a separate pull request for this, but here's as good as anywhere.

EmptyKeys does not have support for Label controls. To counteract this, I modified the generator to emit TextBlocks from Labels. Right now, this is a simple conversion and isn't perfect, but it's better to support Label controls in some way than not at all.

**Comment by EmptyKeys** [comment]
To be honest there is no reason to support Label. Labels were old way from WinForms and pretty much died (no label control in new XAML like Win Store etc.). If you need it, because you are porting some old XAML then it's OK, but I won't support Label in lib.

**Comment by ala53** [comment]
Reverted. :)

**Comment by EmptyKeys** [comment]
feature added, tho I had to merge it locally. Closing :)

**Pull request closed without merging**
